"""Initial_schema

Revision ID: 84db2cfe5eb8
Revises: 
Create Date: 2026-02-01 17:32:52.922350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84db2cfe5eb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=5), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('league', sa.String(length=10), nullable=False),
    sa.Column('offensive_dvoa', sa.Float(), nullable=True),
    sa.Column('defensive_dvoa', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_abbreviation'), 'teams', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_teams_league'), 'teams', ['league'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_table('venues',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('is_dome', sa.Boolean(), nullable=False),
    sa.Column('is_retractable', sa.Boolean(), nullable=False),
    sa.Column('surface_type', sa.String(length=20), nullable=True),
    sa.Column('elevation_ft', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=False)
    op.create_table('games',
    sa.Column('sport', sa.String(length=10), nullable=False),
    sa.Column('home_team_id', sa.UUID(), nullable=False),
    sa.Column('away_team_id', sa.UUID(), nullable=False),
    sa.Column('commence_time', sa.DateTime(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('temperature_f', sa.Integer(), nullable=True),
    sa.Column('wind_mph', sa.Integer(), nullable=True),
    sa.Column('precipitation_prob', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_commence_time'), 'games', ['commence_time'], unique=False)
    op.create_index(op.f('ix_games_sport'), 'games', ['sport'], unique=False)
    op.create_table('players',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('jersey_number', sa.String(length=3), nullable=True),
    sa.Column('injury_status', sa.String(length=20), nullable=True),
    sa.Column('injury_impact', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    op.create_table('parlay_recommendations',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('legs', sa.JSON(), nullable=False),
    sa.Column('num_legs', sa.Integer(), nullable=False),
    sa.Column('true_probability', sa.Float(), nullable=False),
    sa.Column('implied_probability', sa.Float(), nullable=False),
    sa.Column('correlation_multiplier', sa.Float(), nullable=False),
    sa.Column('ev_percentage', sa.Float(), nullable=False),
    sa.Column('recommended', sa.String(length=20), nullable=False),
    sa.Column('fair_odds', sa.Float(), nullable=False),
    sa.Column('sportsbook_odds', sa.Float(), nullable=True),
    sa.Column('sportsbook_name', sa.String(length=50), nullable=True),
    sa.Column('regime_detected', sa.String(length=20), nullable=True),
    sa.Column('explanation_factors', sa.JSON(), nullable=True),
    sa.Column('simulation_time_ms', sa.Float(), nullable=True),
    sa.Column('confidence_interval_lower', sa.Float(), nullable=True),
    sa.Column('confidence_interval_upper', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_correlations',
    sa.Column('player_1_id', sa.UUID(), nullable=False),
    sa.Column('player_2_id', sa.UUID(), nullable=False),
    sa.Column('stat_1', sa.String(length=30), nullable=False),
    sa.Column('stat_2', sa.String(length=30), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_2_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_1_id', 'stat_1', 'player_2_id', 'stat_2', name='uq_player_correlation')
    )
    op.create_index('idx_correlation_lookup', 'player_correlations', ['player_1_id', 'player_2_id'], unique=False)
    op.create_table('player_marginals',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('stat_type', sa.String(length=30), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('std_dev', sa.Float(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('over_probability', sa.Float(), nullable=False),
    sa.Column('under_probability', sa.Float(), nullable=False),
    sa.Column('over_odds', sa.Float(), nullable=True),
    sa.Column('under_odds', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_player_game_stat', 'player_marginals', ['player_id', 'game_id', 'stat_type'], unique=False)
    op.create_index(op.f('ix_player_marginals_stat_type'), 'player_marginals', ['stat_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_marginals_stat_type'), table_name='player_marginals')
    op.drop_index('idx_player_game_stat', table_name='player_marginals')
    op.drop_table('player_marginals')
    op.drop_index('idx_correlation_lookup', table_name='player_correlations')
    op.drop_table('player_correlations')
    op.drop_table('parlay_recommendations')
    op.drop_index(op.f('ix_players_position'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_sport'), table_name='games')
    op.drop_index(op.f('ix_games_commence_time'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_league'), table_name='teams')
    op.drop_index(op.f('ix_teams_abbreviation'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
